apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics-test
  newTag: 55851625fc5351ebf1c441188f7445756eafaf17
kind: Kustomization
namespace: xihe-test-v2
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-deployment.yaml
