apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- service.yaml
commonLabels:
  component: synchronizer
nameSuffix: -synchronizer
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github-synchronizer
  newTag: main-8468835
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github-synchronizer
  newTag: main-c75d56
