apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-website-api
  newTag: master-53264e
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/website-backend
  newTag: old-version-95dc7d
namespace: website
resources:
- namespace.yaml
- pvc.yaml
- console.yaml
- website-api.yaml
