resources:
- namespace.yaml
- secret.yaml
- internal-server
- message-server
- hook-delivery
- sync-repo
- training-center-huaweicloud
- inference-evaluate
- xihe-website
- xihe-server
- xihe-script
- big-model-finetune
- finetune
- xihe-statistics
- async-server
- aicc-finetune
namespace: xihe-new
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
