apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-secret
  namespace: mindspore-doc-search
spec:
  keysMap:
    xarmor_app_id:
      key: xarmor_app_id
      path: secrets/data/mindspore/rasp_secret
    xarmor_backend_url:
      key: xarmor_backend_url
      path: secrets/data/mindspore/rasp_secret
    xarmor_tenant_id:
      key: xarmor_tenant_id
      path: secrets/data/mindspore/rasp_secret
    xarmor_backend_app_token:
      key: xarmor_backend_app_token
      path: secrets/data/mindspore/rasp_secret
    xarmor_security_enable:
      key: xarmor_security_enable
      path: secrets/data/mindspore/rasp_secret
    xarmor_security_root_password:
      key: xarmor_security_root_password
      path: secrets/data/mindspore/rasp_secret
    xarmor_secutiry_work_password:
      key: xarmor_secutiry_work_password
      path: secrets/data/mindspore/rasp_secret
  name: doc-search-secret

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-tls
  namespace: mindspore-doc-search
spec:
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.cert
    tls.crt:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.cert
    tls.key:
      path: secrets/data/mindspore/mindspore-cn-tls
      key: ca.key
  name: doc-search-tls

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-osinfra-tls
  namespace: mindspore-doc-search
spec:
  name: doc-search-osinfra-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key
