---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-aicc-finetune
  namespace: xihe-test-v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aicc-finetune
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0700"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: "internal/data/mindspore/xihe-test-v2"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-test-v2" -}}
          {{ .Data.data.aiccfinetune }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        app: aicc-finetune
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: aicc-finetune
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-aicc-finetune:test1-8e7a4c
        imagePullPolicy: IfNotPresent
        args:
        - --port=8080
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=true
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
