---
apiVersion: v1
kind: Service
metadata:
  name: xihe-aicc-finetune-service
  namespace: xihe-test-v2
spec:
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
  selector:
    app: aicc-finetune
  type: ClusterIP
