---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-server
  namespace: xihe-new
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xihe-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0700"
        vault.hashicorp.com/agent-inject-perms-ca.crt: "0700"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: "internal/data/mindspore/xihe-new"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-new" -}}
          {{ .Data.data.Server }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ca.crt: "internal/data/mindspore/xihe-new"
        vault.hashicorp.com/agent-inject-template-ca.crt: |
          {{- with secret "internal/data/mindspore/xihe-new" -}}
          {{ .Data.data.MongoCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-new
      labels:
        app: xihe-server
    spec:
      serviceAccount: xihe-new
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: xihe-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server:ac05fa60730a2ad5baa210bf1aea9904aed96ff5
        imagePullPolicy: IfNotPresent
        args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=true
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 4000m
            memory: 4000Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
