apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics
  newTag: 9217fe6208baaa61852558f2be9840c6ae54a039
kind: Kustomization
namespace: xihe-new
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-secret.yaml
- xihe-statistics-deployment.yaml
