apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics
  newTag: da0f7436f935f86ba56ef5c943b576a86fdfe23e
kind: Kustomization
namespace: xihe-new
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-deployment.yaml
