apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics
  newTag: e66d05305f8496af7598c541c881829587bbfa60
kind: Kustomization
namespace: xihe-new
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-deployment.yaml
- secret.yaml
