apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics
  newTag: c281c0c15744181b8053337362e679e3eceb9ea9
kind: Kustomization
namespace: xihe-new
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-deployment.yaml
- secret.yaml
