apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-new
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0700"
        vault.hashicorp.com/agent-inject-perms-ca.crt: "0700"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: "internal/data/mindspore/xihe-new"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-new" -}}
          {{ .Data.data.messageServer }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ca.crt: "internal/data/mindspore/xihe-new"
        vault.hashicorp.com/agent-inject-template-ca.crt: |
          {{- with secret "internal/data/mindspore/xihe-new" -}}
          {{ .Data.data.MongoCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-new
    spec:
      serviceAccount: xihe-new
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: message-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=true
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
