apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-usercenter
  newTag: 68b284f9f417acd0b88967e56ab5b10cfdf44ce3
kind: Kustomization
namespace: mindspore-usercenter
resources:
- namespace.yaml
- website-ingress.yaml
- website-service.yaml
- website-deployment.yaml
- secret.yaml
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn4-x86
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: chenqi
  kubernetes.ops.region: beijing
