apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-new
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-kubeconfig.json: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: "internal/data/mindspore/xihe-new"
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "internal/data/mindspore/xihe-new" -}}
          {{ .Data.data.inferenceEvaluate }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-kubeconfig.json: "internal/data/mindspore/xihe-new"
        vault.hashicorp.com/agent-inject-template-kubeconfig.json: |
          {{- with secret "internal/data/mindspore/xihe-new" -}}
          {{ .Data.data.kubeconfig }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-new
    spec:
      serviceAccount: xihe-new
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=true
        env:
        - name: INFERENCE_IMAGE
          value: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-inference-evaluate:dev-fdcae9
        - name: INFERENCE_INIT_IMAGE
          value: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-inference-evaluate-init:dev-fdcae9
        - name: CLOUD_IMAGE
          value: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-jupyter-cpu:dev-fdcae9
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        name: inference-evaluate
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
