---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website-revision
spec:
  replicas: 0
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: websiteinfod
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-website:master-51dab8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-v2
  namespace: website-revision
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  selector:
    matchLabels:
      app: website-v2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
        vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0600"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
        vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/mindspore/mindspore-website"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with secret "internal/data/mindspore/mindspore-website" -}}
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/mindspore/mindspore-website"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "internal/data/mindspore/mindspore-website" -}}
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/mindspore/mindspore-website"
        vault.hashicorp.com/agent-inject-template-abc.txt: |
          {{- with secret "internal/data/mindspore/mindspore-website" -}}
          {{ .Data.data.certificatePassword }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/mindspore/mindspore-website"
        vault.hashicorp.com/agent-inject-template-dhparam.pem: |
          {{- with secret "internal/data/mindspore/mindspore-website" -}}
          {{ .Data.data.dhparamPem }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: mindspore-website
      labels:
        app: website-v2
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccount: mindspore-website
      containers:
      - name: websiteinfod
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-website:v1.0.20231218203159
        imagePullPolicy: IfNotPresent
        env:
        - name: DET_URL
          value: https://www.mindspore.cn
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
            httpHeaders:
            - name: "Host"
              value: "www.mindspore.cn"
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
            httpHeaders:
            - name: "Host"
              value: "www.mindspore.cn"
          timeoutSeconds: 10
