---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/permanent-redirect: https://download-mindspore.osinfra.cn$request_uri
  name: repo-ingress
  namespace: download
spec:
  tls:
    - hosts:
        - download.mindspore.cn
      secretName: download-secrets
  rules:
    - host: download.mindspore.cn

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: repo-download-osinfra-ingress
  namespace: download
spec:
  tls:
    - hosts:
        - download-mindspore.osinfra.cn
      secretName: download-osinfra-tls
  rules:
    - host: download-mindspore.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: repo-service
              servicePort: 80
            path: /
