apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  component: internal-server
nameSuffix: -internal-server
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-internal-server
  newTag: main-fd17336
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-internal-server
  newTag: 0b337f38746e77a51e591e55500db28340de910c
