apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    finetune_endpoint: "${FINETUNE_ENDPOINT}"

    mongodb:
      db_conn: "${MONGODB_CONNECTION}"
      db_name: "${MONGODB_NAME}"
      db_cert: "${MONGODB_CERT}"
      collections:
        project: project
        model: model
        dataset: dataset
        user: user
        registration: registration
        login: login
        like: like
        activity: activity
        tag: tag
        luojia: luojia
        wukong: wukong
        training: training
        finetune: finetune
        evaluate: evaluate
        inference: inference
        aiquestion: aiquestion
        competition: competition
        question_pool: questionpool
        wukong_picture: wukongpicture
        competition_work: competition_work
        competition_player: competition_player
        course: course
        course_player: course_player
        course_work: course_work
        course_record: course_record
        cloud_conf: cloud_conf
        api_apply: api_apply
        api_info: api_info
        points_task: points_task
        user_points: user_points
        aicc_finetune: aicc_finuetune

    postgresql:
      db:
        host: "${PGSQL_HOST}"
        user: "${PGSQL_USER}"
        pwd: "${PGSQL_PWD}"
        name: "${PGSQL_NAME}"
        port: ${PGSQL_PORT}
        life:
      cloud:
        table:
          pod: pod
      async:
        table:
          async_task: async_task

    redis:
      address: "${REDIS_ADDRESS}"
      password: "${REDIS_PASSWORD}"
      key_pair: "${KEY_PAIR}"

    domain:
      min_name_length: 3
      max_name_length: 35
      max_desc_length: 200
      max_title_length: 105
      min_title_length: 3
      min_training_name_length: 5
      max_training_name_length: 50
      max_training_desc_length: 256
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache-2.0"
      - "mit"
      - "cc-by-sa-3.0"
      - "afl-3.0"
      - "cc-by-sa-4.0"
      - "lgpl-3.0"
      - "lgpl-lr"
      - "cc-by-nc-3.0"
      - "bsd-2-clause"
      - "ecl-2.0"
      - "cc-by-nc-sa-4.0"
      - "cc-by-nc-4.0"
      - "gpl-3.0"
      - "cc0-1.0"
      - "cc"
      - "bsd-3-clause"
      - "agpl-3.0"
      - "wtfpl"
      - "artistic-2.0"
      - "postgresql"
      - "gpl-2.0"
      - "isc"
      - "eupl-1.1"
      - "pddl"
      - "bsd-3-clause-clear"
      - "mpl-2.0"
      - "odbl-1.0"
      - "cc-by-4.0"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"

      finetunes:
        opt-caption:
          tasks:
          - finetune
          hyperparameters:
          - epochs
          - start_learning_rate
          - end_learning_rate

      avatar_url:
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-3.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-2.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-1.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/common-4.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_01.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_02.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_03.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_04.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_05.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_06.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_07.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/catimg_08.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-1.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-2.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-3.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/man-4.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-1.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-2.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-3.png"
      - "https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/xihe-img/default_avatar/woman-4.png"


    mq:
      address: "${KAFKA_ADDRESS}"
      version: "2.3.0"

    mq_topics:
      fork: "xihe_fork_test"
      like: "xihe_like_test"
      cloud: "xihe_jupyter_created_test"
      download: "xihe_download_test"
      evaluate: "xihe_evaluate_test"
      training: "xihe_training_test"
      aiccfinetune: "xihe_aiccfinetune_test"
      finetune: "xihe_finetune_test"
      inference: "xihe_inference_test"
      following: "xihe_following_test"
      submission: "xihe_submission_test"
      operate_log: "xihe_operate_log_test"
      related_resource: "xihe_related_resource_test"
      async: "xihe_async_test"
      signin: "xihe_sign_in_test"
      bigmodel_topics:
        inference_start: "xihe_inference_start_test"
        inference_error: "xihe_inference_error_test"
        inference_async_start: "xihe_inference_async_start_test"
        inference_async_finish: "xihe_inference_async_finish_test"
        bigmodel_finished: "xihe_bigmodel_finished_test"
      picture_publicized: "xihe_picture_publicized_test"
      picture_liked: "xihe_picture_liked_test"
      competitor_applied: "xihe_competitor_applied_test"
      jupyter_created: "xihe_jupyter_created_test"
      course_applied: "xihe_course_applied_test"
      training_created: "xihe_training_created_test"
      project_created: "xihe_create_project_test"
      model_created: "xihe_create_model_test"
      dataset_created: "xihe_create_dataset_test"
      project_downloaded: "xihe_download_project_test"
      dataset_downloaded: "xihe_download_dataset_test"
      model_downloaded: "xihe_download_model_test"
      user:
        bio_set: "xihe_set_bio_test"
        avatar_set: "xihe_set_avatar_test"
        user_signed_up: "xihe_sign_up_test"
        following_added: "xihe_following_add_test"
        following_removed: "xihe_following_remove_test"
      aicc_finetune_created: "aicc_finetune_created_test"

    evaluate:
      endpoint: "${INFERENCE_EVALUATE_ENDPOINT}"
      survival_time: 10800

    inference:
      endpoint: "${INFERENCE_EVALUATE_ENDPOINT}"
      project_tags_for_official:
      - "official"

    cloud:
      endpoint: "${INFERENCE_EVALUATE_ENDPOINT}"
      survival_time: 7200

    training:
      training_endpoint: "${TRAINING_ENDPOINT}"

    aiccfinetune:
      aiccfinetune_endpoint: "${AICC_FINETUNE_ENDPOINT}"
