apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
commonLabels:
  component: message-server
nameSuffix: -message-server
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-message-server
  newTag: main-47cdabc
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-message-server
  newTag: 9cf9b51fa202b2ce3765af7892ff7f67993ac32e
