apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
commonLabels:
  component: message-server
nameSuffix: -message-server
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-message-server
  newTag: main-47cdabc
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-message-server
  newTag: 78ecf342c89cd2219103241735565d5f54ef4719
