apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  component: training-center-huaweicloud
nameSuffix: -training-center-huaweicloud
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-training-center
  newTag: main-ab5e153
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-training-center
  newTag: v1.0.20230908152123
