apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- cla
- welcome
- review
- label
- lifecycle
- assign
- repo-watcher-openeuler
- repo-watcher-src-openeuler
commonLabels:
  app: infrastructure-robot-github
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-github-openeuler
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github-openeuler-repo-watcher
  newTag: main-ca85bc
