apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - mindspore/models
      need_welcome: true
      cla_label: "mindspore-cla/yes"
      review:
        total_number_of_approvers: 2
        total_number_of_reviewers: 2
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"
    - repos:
      - mindspore/vision
      need_welcome: true
      cla_label: "mindspore-cla/yes"
      review:
        total_number_of_approvers: 1
        total_number_of_reviewers: 2
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"
      owner:
        branch_without_owners: ".*"
    - repos:
      - mindspore/graphlearning
      need_welcome: true
      cla_label: "mindspore-cla/yes"
      review:
        total_number_of_approvers: 2
        total_number_of_reviewers: 2
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"
      owner:
        branch_with_owners:
        - master
    - repos:
      - mindspore/mindspore
      - mindspore/community
      - mindspore/mindvision
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 1
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"

    - repos:
      - mindspore/course
      - mindspore/federated
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 2
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"

    - repos:
      - mindspore/golden-stick
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 1
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"

    - repos:
      - mindspore/mindpandas
      - mindspore/recommender
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 2
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 2
        label_for_ci_passed: "ci-pipeline-passed"

    - repos:
      - mindspore/graphengine
      - mindspore/mindspore.github.io
      - mindspore/serving
      - mindspore/mindquantum
      - mindspore/mindtext
      - mindspore/xai
      - mindspore/akg
      - mindspore/sault
      - mindspore/hub
      - mindspore/dataset-plugin
      - mindspore/mindarmour
      - mindspore/akg-full-log
      - mindspore/book
      - mindspore/docs
      - mindspore/text
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 1
      ci:
        job:
          ci_table:
            title: "| Project Name | Build Result | Details |"
            result_column_num: 2
          job_success_status:
          - "SUCCESS"
        number_of_test_cases: 1
        label_for_ci_passed: "ci-pipeline-passed"

    - repos:
      - mindspore/ms-pipeline
      - mindspore/darglint
      - mindspore/contrib
      - mindspore/topenterprise
      - mindspore/blog
      - mindspore/ms-operator
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 1
      ci:
        no_ci: true

    - repos:
      - mindspore/reinforcement
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 1
      ci:
        no_ci: true
    commands_endpoint: "https://prow.osinfra.cn/gitee-deck/command-help?repo="
    doc: "You can get details about the review process of pull-request at [**here**](https://github.com/opensourceways/test-infra/blob/sync-5-22/prow/gitee-plugins/review-trigger/review.md)"
