apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-secrets
  namespace: repo
spec:
  name: website-secrets
  keysMap:
    rsyncd_secrets:
      path: secrets/data/mindspore/repo
      key: rsyncd.secrets
    auth_files:
      path: secrets/data/mindspore/repo
      key: auth_files

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: repo-new-tls
spec:
  name: repo-new-tls
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/website-secrets
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: repo-osinfra-tls
  namespace: repo
spec:
  name: repo-osinfra-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key

