apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: om-webserver-secrets
  namespace: om-webserver-xihe
spec:
  name: om-webserver-secrets
  keysMap:
    application_properties:
      path: secrets/data/infra-common/om
      key: application_xihe_properties

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
 name: tls-secrets
spec:
 name: tls-secrets
 keysMap:
   ca.crt:
     path: secrets/data/infra-common/osinfra
     key: tls.cert
   tls.crt:
     path: secrets/data/infra-common/osinfra
     key: tls.cert
   tls.key:
     path: secrets/data/infra-common/osinfra
     key: tls.key
